### ISSUE TITLE
Missing item weight in full_deploy_code

### ISSUE THREAD

**Issue by johnwayne1930** [bytePro17124/CustomArkLootDrops#6]
New ASM v1.0.259.4 say's there is an item weight missing from "PrimalItemConsumable_Egg_Spider_C" on some of the crates (blue to red i think) from standard full_deploy_code.

Same on the Scorched Earth code with "PrimalItemArmor_TapejaraSaddle_C" from crate blue to red.

**Comment by mattearly** [comment]
Thanks, I'll get those fixed
